image: alpine

before_script:
- apk update
- apk add doxygen
## Uncomment the following line if you use graphviz dot graphs
- apk add ttf-freefont graphviz

test:
  script:
  - doxygen doc/sfl.doxy
  except:
  - master
  
pages:
  script:
  - doxygen doc/sfl.doxy
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
